- hosts: all
  user: ec2-user
  become: yes
  tasks:
    - name: 'Update packages'
      yum:
        name: '*'
        state: latest
    - name: 'Install yum-utils'
      yum:
        name: 'yum-utils'
        state: present
    - name: 'Install yum Development tools'
      yum:
        name: "@Development tools"
        state: present
    - name: 'Install epel repo'
      yum:
        name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
        state: present
    - name: 'Install ius repo'
      yum:
        name: https://repo.ius.io/ius-release-el7.rpm
        state: present
    - name: 'Install Python 3.6'
      yum:
        name: python36
        state: present
    - name: 'Install Python 3.6 Development tools'
      yum:
        name: python36-devel
        state: present
    - name: 'Install pip'
      yum:
        name: python36-pip
        state: present
    - name: 'Install nfs-utils'
      yum:
        name: nfs-utils
        state: present
    - name: 'Install PostgreSQL driver'
      pip:
        name: "apache-airflow[aws, kubernetes, postgres]"
        executable: pip3.6
    - name: 'Create home directory for Airflow'
      file:
        path: /home/ec2-user/airflow
        state: directory
        owner: ec2-user
        group: ec2-user
        mode: '0755'
    - name: 'Create directory for aws-iam-authenticator'
      file:
        path: /home/ec2-user/bin
        state: directory
        owner: ec2-user
        group: ec2-user
        mode: '0755'
    - name: 'Copy airflow config to home airflow directory'
      copy:
        src: ./airflow.cfg
        dest: /home/ec2-user/airflow
        owner: ec2-user
    - name: 'Install kubectl and aws-ias-authenticator'
      script: kubernetes.sh
      args:
        chdir:
          /home/ec2-user/
    - name: 'Change owener and group of aws-iam-authenticator'
      file:
        path: /home/ec2-user/bin/aws-iam-authenticator
        owner: ec2-user
        group: ec2-user
    - name: 'Create direcotry for kubeconfig'
      file:
        path: /home/ec2-user/.kube
        state: directory
        owner: ec2-user
        group: ec2-user
        mode: '0755'
    - name: 'Copy kubeconfig to .kube'
      copy:
        src: ./../eks/kubeconfig_airflow-cluster
        owner: ec2-user
        group: ec2-user
        dest: /home/ec2-user/.kube/config
