apiVersion: v1
kind: PersistentVolume
metadata:
  name: dags
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: airflow
    name: dags
  nfs:
    server: fs-7804d500.efs.us-east-2.amazonaws.com
    path: /