output "cluster_endpoint" {
  description = "Endpoint for EKS control plane."
  value = module.airflow-cluster.cluster_endpoint
}

output "kubectl_config" {
  description = "kubectl config as generated by the module."
  value = module.airflow-cluster.kubeconfig
}

output "config_map_aws_auth" {
  description = "A kubernetes configuration to authenticate to this EKS cluster."
  value = module.airflow-cluster.config_map_aws_auth
}